version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - pip install -r requirements.txt
      - python -m unittest discover

artifacts:
  files:
    - '**/*'
  discard-paths: yes

